/**
 * Login verifier — generated by `npm run set-password`. Do not edit by hand.
 *
 * This file is safe to commit: it holds a salt and a ciphertext, not the
 * password. See scripts/make-verifier.mjs for how it is used.
 */

export const ITERATIONS = 600000;
export const SENTINEL = 'toms-tools:vault:v1:';
export const SALT = '9xA126fOnqklwXFG839B8w==';
export const CHECK = { iv: 'sWyDWovvFv5G8Kbs', ct: 'a7Z45DEG7HolLQcBwNM/wcPyz40deCwOs8ajWzP3azymcxfhXCphO73OCJBd8OPq06eMhz7686LjNA==' };
